# Generated by Django 2.0.1 on 2018-03-25 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price0', models.CharField(max_length=32)),
                ('price1', models.CharField(max_length=32)),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_of_catering', to='speiseplan.Catering')),
            ],
        ),
        migrations.CreateModel(
            name='MealDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealdate', to='speiseplan.Catering')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='mealdate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_of_mealdate', to='speiseplan.MealDate'),
        ),
    ]
