# Generated by Django 2.0.1 on 2018-05-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speiseplan', '0002_auto_20180525_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdate',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
